<a href="https://colab.research.google.com/github/mesrp88/numpy_pandas_uses/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x= np.array(values)

In [3]:
even_value= x[x%2==0]  # here I collected even value
even_value

array([4, 8, 0, 2, 6])

In [4]:
 even_index_value= x[0::2] # here I collected even index value
 even_index_value

array([7, 5, 9, 1, 2])

In [5]:
odd_index_value=x[1::2] #here I Collected odd index value
odd_index_value

array([4, 8, 0, 3, 6])

In [6]:
reverse=x[-1::-1] #reversing above element
reverse

array([6, 2, 3, 1, 0, 9, 8, 5, 4, 7])

Create first_half function which take 1d array if array have even num take first half element if array have odd num take first half amd middle element

In [13]:
def first_half(x):
  if len(x)%2==0:
    print('Even')
    return x[:len(x)//2]
  elif len(x)%2!=0:
    print('Odd')
    return x[:(len(x)//2+1)]

x=np.array([1,2,3,4,5])
print(first_half(x))


Odd
[1 2 3]


In [12]:
xx=np.array([1,2,3,4])
print(first_half(xx))

even
[1 2]


In [14]:
def second_half(x):
     return x[len(x)//2:]

In [16]:
xx=np.array([1,2,3,4])
print(first_half(xx))

Even
[1 2]


In [20]:
values1 = [5, 7, 4, 6, 3, 9]
values2 = [2, 1, 8, 0]
x=np.array(values1)
y= np.array(values2)
concat= np.concatenate([x,y])
concat

array([5, 7, 4, 6, 3, 9, 2, 1, 8, 0])

In [21]:
def mix(x,y):
    X=x[:len(x)//2]
    Y=y[len(y)//2:]
    return np.concatenate([X,Y])




x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)
print(z)

[ 1  2  8  9 10]


In [23]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x= np.array(values)
reverse_skip= x[-1::-2]
reverse_skip

array([6, 3, 0, 8, 4])

In [24]:
values = [
    [5, 6, 5, 5, 8, 9, 9], 
    [9, 5, 1, 4, 5, 9, 7], 
    [3, 9, 6, 2, 1, 2, 3], 
    [1, 7, 6, 7, 1, 7, 5], 
    [2, 1, 3, 8, 7, 8, 8], 
    [2, 9, 3, 6, 4, 6, 4]
]

desire=[
       [4, 6, 4, 6, 3, 9, 2],
       [8, 8, 7, 8, 3, 1, 2],
       [5, 7, 1, 7, 6, 7, 1],
       [3, 2, 1, 2, 6, 9, 3],
       [7, 9, 5, 4, 1, 5, 9],
       [9, 9, 8, 5, 5, 6, 5]
]

x=np.array(values)
x1= x[-1::-1]
reverse_2d= x1[:,-1::-1]
reverse_2d

array([[4, 6, 4, 6, 3, 9, 2],
       [8, 8, 7, 8, 3, 1, 2],
       [5, 7, 1, 7, 6, 7, 1],
       [3, 2, 1, 2, 6, 9, 3],
       [7, 9, 5, 4, 1, 5, 9],
       [9, 9, 8, 5, 5, 6, 5]])

In [26]:

def select_rows(x, row_indexes):
    return x[row_indexes]

# Uncomment to test
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
rows_1_4_3



array([[ 5,  6,  7,  8],
       [17, 18, 19, 20],
       [13, 14, 15, 16]])

In [27]:
def select_columns(x, col_indexes):
    return x[:,col_indexes]
    
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0])
print(cols_3_0)

[[ 4  1]
 [ 8  5]
 [12  9]
 [16 13]
 [20 17]]


In [30]:
def copy_row_k_times(x, row_index, row_k_times):
    return x[[row_index]*row_k_times]
    


# Uncomment to test
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [31]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x=array2d[:,1:3]
y=array2d[[0,2]]
z= array2d[2, 1:4]

In [32]:
x

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [33]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [34]:
z

array([12, 13, 14])

In [35]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x= array2d[[1,3],::2]
y= array2d[[0,2],1::2]
z=array2d[[0,2],1:4]

In [36]:
x

array([[ 6,  8, 10],
       [16, 18, 20]])

In [38]:
y

array([[ 2,  4],
       [12, 14]])

In [39]:
z

array([[ 2,  3,  4],
       [12, 13, 14]])

swapping case

In [40]:
a=3;b=4
b,a=a,b

In [41]:
b

3

In [42]:
a

4

here I swap rows

In [44]:
def swap_rows(x, row_index1, row_index2):
    x[[row_index2, row_index1]]=x[[row_index1, row_index2]]
    return x


# Uncomment to test
x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


next approach could be

In [50]:
def swap_rows(x, row_index1, row_index2):
  row_tem= x[row_index1].copy()
  x[row_index1]= x[row_index2]
  x[row_index2]= row_tem

x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [51]:
def swap_cols(x, col_index1, col_index2):
    x[:,[col_index2,col_index1]]= x[:,[col_index1,col_index2]]


# Uncomment to test
x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]


In [52]:
def swap_cols(x, col_index1, col_index2):
  tem_col= x[:,col_index1].copy()
  x[:,col_index1]= x[:,col_index2]
  x[:, col_index2]= tem_col

x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
