<a href="https://colab.research.google.com/github/mesrp88/numpy_pandas_uses/blob/main/numpy_and_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing libraries
import numpy as np 
import pandas as pd


In [2]:
data_ndarray= np.array([10,20,30])
data_ndarray

array([10, 20, 30])

In [3]:
from csv import reader

f= open('/content/nyc_taxis.csv', 'r')
taxi_list=list(reader(f))
taxi_list= taxi_list[1:]
taxi_list[:1]

[['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '4',
  '21.00',
  '2037',
  '52.00',
  '0.80',
  '5.54',
  '11.65',
  '69.99',
  '1']]

In [4]:
#converting all value into float data_type
converted_taxi_list=[]
for row in taxi_list:
  converted_row=[]
  for item in row:
    converted_row.append(float(item))
  converted_taxi_list.append(converted_row)
converted_taxi_list[:1]

[[2016.0,
  1.0,
  1.0,
  5.0,
  0.0,
  2.0,
  4.0,
  21.0,
  2037.0,
  52.0,
  0.8,
  5.54,
  11.65,
  69.99,
  1.0]]

In [5]:
#change into nunpy  array
taxi= np.array(converted_taxi_list)
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [6]:
#to know number of rows and columns)
taxi_shape=taxi.shape
taxi_shape

(2013, 15)

In [7]:
row_0=taxi[0]
print(row_0)
print('\n')
rows_391_to_500= taxi[391:501]
print(rows_391_to_500)
print('\n')
row_21_column_5= taxi[21,5]
print(row_21_column_5)

[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]


[[2.016e+03 1.000e+00 2.000e+00 ... 0.000e+00 2.630e+01 2.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 3.000e+00 3.030e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 6.670e+00 4.001e+01 1.000e+00]
 ...
 [2.016e+03 1.000e+00 4.000e+00 ... 0.000e+00 5.534e+01 2.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 3.090e+00 1.339e+01 1.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 4.000e+00 2.680e+01 1.000e+00]]


4.0


In [8]:
columns_1_4_7= taxi[:,[1,4,7]]
print(columns_1_4_7)
print('\n')
row_99_columns_5_to_8= taxi[99,5:9]
print(row_99_columns_5_to_8)
print('\n')
rows_100_to_200_column_14= taxi[100:201, 14]
print(rows_100_to_200_column_14)


[[ 1.    0.   21.  ]
 [ 1.    0.   16.29]
 [ 1.    0.   12.7 ]
 ...
 [ 6.    5.   17.48]
 [ 6.    5.   12.76]
 [ 6.    5.   17.54]]


[   2.      4.     20.91 1744.  ]


[2. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1. 2. 1. 2. 1. 1. 2. 2.
 2. 1. 1. 2. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2.
 2. 2. 1. 4. 2. 1. 2. 1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 2. 1. 2. 2. 1.
 2. 1. 2. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 2.]


In [9]:
#vector addition
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]
fare_and_fees= fare_amount+fees_amount
fare_and_fees

array([52.8, 46.3, 37.8, ..., 52.8, 35.8, 49.3])

In [10]:
array2d= np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [11]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
array2d.max(axis=1)

array([3, 6, 9])

In [13]:
array2d.max(axis=0)

array([7, 8, 9])

In [14]:
array2d.max()

9

Boolean Indexing 

In [15]:
taxi= np.genfromtxt('nyc_taxis.csv', delimiter=',')
taxi_shape= taxi.shape

print(taxi_shape,'\n')
print(taxi.dtype)

(2014, 15) 

float64


In [16]:
taxi

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [17]:
taxi=taxi[1:]
taxi

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 1.165e+01, 6.999e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 8.000e+00, 5.430e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [18]:
taxi= np.genfromtxt('nyc_taxis.csv', delimiter=',', skip_header= 1)
taxi_shape= taxi.shape
taxi_shape

(2013, 15)

In [19]:
print(np.array([1,2,3,4,5])+10) #10  is added to every element inside array

[11 12 13 14 15]


In [20]:
print(np.array([1,2,3,4,5])<3)

[ True  True False False False]


In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

a_bool= a<3
a_bool


array([ True,  True, False, False, False])

In [22]:
b_bool= b=='blue'
b_bool

array([ True,  True, False,  True])

In [23]:
c_bool= c>100
c_bool

array([False,  True, False,  True])

Here I am only selecting element with True value.

In [24]:
pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]
january_rides

800

In [25]:
february_bool= pickup_month==2
february= pickup_month[february_bool]
february_rides=february.shape[0]
february_rides

176

In [26]:
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
print(a)

['orange' 'blue' 'black' 'blue' 'purple']


In [27]:
a[3:] = 'pink'
print(a)

['orange' 'blue' 'black' 'pink' 'pink']


In [28]:
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2] = 99
print(ones)

[[ 1  1  1  1  1]
 [ 1  1 99  1  1]
 [ 1  1  1  1  1]]


In [29]:
ones[0] = 42
print(ones)

[[42 42 42 42 42]
 [ 1  1 99  1  1]
 [ 1  1  1  1  1]]


In [30]:
ones[:,2] = 0
print(ones)

[[42 42  0 42 42]
 [ 1  1  0  1  1]
 [ 1  1  0  1  1]]


Here element above 2 is changed to 99

In [31]:
a2 = np.array([1, 2, 3, 4, 5])

a2_bool = a2 > 2

a2[a2_bool] = 99

print(a2)

[ 1  2 99 99 99]


direct using boolean assignment

In [32]:
taxi_copy = taxi.copy()
total_amount= taxi_copy[:, 13]
total_amount[total_amount<0]=0

In [33]:
matrix2d= np.array(np.arange(1,10)).reshape(3,-1)
matrix2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Here I assign 99 to every element having value more than 4

In [34]:
matrix2d[matrix2d>4]= 99
matrix2d

array([[ 1,  2,  3],
       [ 4, 99, 99],
       [99, 99, 99]])

In [35]:
m2d= np.array(np.arange(1,10)).reshape(3,-1)
m2d[m2d[:,1]>2]=88 #this is used as row index
m2d

array([[ 1,  2,  3],
       [88, 88, 88],
       [88, 88, 88]])

In [36]:
m2d[m2d[:,1]>2, 1]=99 #this is used as columns index

In [37]:
m2d

array([[ 1,  2,  3],
       [88, 99, 88],
       [88, 99, 88]])

In [38]:
'''bool = array[:, column_for_comparison] == value_for_comparison
array[bool, column_for_assignment] = new_value'''

'bool = array[:, column_for_comparison] == value_for_comparison\narray[bool, column_for_assignment] = new_value'

In [39]:
np.zeros((3,4))  #input should be tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
zeros = np.zeros([taxi.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)
 
#here last column is with value 0 and if column index 5 has value with given 
#condition is 1 to last column otherswise zero
taxi_modified[taxi_modified[:,5]==2, 15]=1  
taxi_modified[taxi_modified[:,5]==3, 15]=1
taxi_modified[taxi_modified[:,5]==5, 15]=1

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


Highest dropoff_location

In [41]:
jfk= taxi[taxi[:,6]==2, 2]
jfk_count=jfk.shape[0]
jfk_count





285

In [42]:
newark= taxi[taxi[:,6]==5, 2]
newark_count=newark.shape[0]
newark_count

2

In [43]:
laguardia= taxi[taxi[:,6]==3, 2]
laguardia_count=laguardia.shape[0]
laguardia_count

308

LEARN ABOUT PANDAS HERE I AM GOING TO WORK WITH DIFFERENT DATASET


In [44]:
import pandas as pd
url='/content/f500.csv'
f500= pd.read_csv(url, index_col=0)
f500.head()

rank  revenues  ...  employees  total_stockholder_equity
company                                   ...                                     
Walmart                      1    485873  ...    2300000                     77798
State Grid                   2    315199  ...     926067                    209456
Sinopec Group                3    267518  ...     713288                    106523
China National Petroleum     4    262573  ...    1512048                    301893
Toyota Motor                 5    254694  ...     364445                    157210

[5 rows x 16 columns]

To remove index header we can use

In [45]:
f500.index.name= None

In [46]:
f500.shape

(500, 16)

In [47]:
type(f500)

pandas.core.frame.DataFrame

In [48]:
f500.head()

rank  revenues  ...  employees  total_stockholder_equity
Walmart                      1    485873  ...    2300000                     77798
State Grid                   2    315199  ...     926067                    209456
Sinopec Group                3    267518  ...     713288                    106523
China National Petroleum     4    262573  ...    1512048                    301893
Toyota Motor                 5    254694  ...     364445                    157210

[5 rows x 16 columns]

In [49]:
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   rank                      500 non-null    int64  
 1   revenues                  500 non-null    int64  
 2   revenue_change            498 non-null    float64
 3   profits                   499 non-null    float64
 4   assets                    500 non-null    int64  
 5   profit_change             436 non-null    float64
 6   ceo                       500 non-null    object 
 7   industry                  500 non-null    object 
 8   sector                    500 non-null    object 
 9   previous_rank             500 non-null    int64  
 10  country                   500 non-null    object 
 11  hq_location               500 non-null    object 
 12  website                   500 non-null    object 
 13  years_on_global_500_list  500 non-null    int64  
 14  em

Two ways to select specific columns

In [50]:
industries= f500.loc[:, 'industry']
industries.head()

Walmart                        General Merchandisers
State Grid                                 Utilities
Sinopec Group                     Petroleum Refining
China National Petroleum          Petroleum Refining
Toyota Motor                Motor Vehicles and Parts
Name: industry, dtype: object

In [51]:
industries_type= type(industries)
industries_type

pandas.core.series.Series

In [52]:
industries= f500['industry']
industries

Walmart                                     General Merchandisers
State Grid                                              Utilities
Sinopec Group                                  Petroleum Refining
China National Petroleum                       Petroleum Refining
Toyota Motor                             Motor Vehicles and Parts
                                               ...               
Teva Pharmaceutical Industries                    Pharmaceuticals
New China Life Insurance          Insurance: Life, Health (stock)
Wm. Morrison Supermarkets                    Food and Drug Stores
TUI                                               Travel Services
AutoNation                                    Specialty Retailers
Name: industry, Length: 500, dtype: object

In [53]:
revenues_years= f500[['revenues', 'years_on_global_500_list']]
revenues_years.head()

revenues  years_on_global_500_list
Walmart                     485873                        23
State Grid                  315199                        17
Sinopec Group               267518                        19
China National Petroleum    262573                        17
Toyota Motor                254694                        23

In [54]:
ceo_to_sector= f500.loc[:,'ceo':'sector']
ceo_to_sector.head()

ceo  ...                  sector
Walmart                   C. Douglas McMillon  ...               Retailing
State Grid                            Kou Wei  ...                  Energy
Sinopec Group                       Wang Yupu  ...                  Energy
China National Petroleum        Zhang Jianhua  ...                  Energy
Toyota Motor                      Akio Toyoda  ...  Motor Vehicles & Parts

[5 rows x 3 columns]

SELECTING ROWS

In [55]:
toyota= f500.loc['Toyota Motor']
toyota

rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                          8
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
Name: Toyota Motor, dtype: object

In [56]:
type(toyota)

pandas.core.series.Series

In [57]:
 drink_companies= f500.loc[['Anheuser-Busch InBev', 'Coca-Cola', 'Heineken Holding']]
 drink_companies

rank  revenues  ...  employees  total_stockholder_equity
Anheuser-Busch InBev   206     45905  ...     206633                     71339
Coca-Cola              235     41863  ...     100300                     23062
Heineken Holding       468     23044  ...      73525                      6958

[3 rows x 16 columns]

In [58]:
type(drink_companies)

pandas.core.frame.DataFrame

In [59]:
middle_companies= f500.loc['Tata Motors': 'Nationwide', 'rank':'country']
middle_companies.head()

rank  revenues  ...  previous_rank  country
Tata Motors               247     40329  ...            226    India
Aluminum Corp. of China   248     40278  ...            262    China
Mitsui                    249     40275  ...            245    Japan
Manulife Financial        250     40238  ...            394   Canada
China Minsheng Banking    251     40234  ...            221    China

[5 rows x 11 columns]

In [60]:
countries_value= f500['country'].value_counts()
countries_value



USA             132
China           109
Japan            51
France           29
Germany          29
Britain          24
South Korea      15
Netherlands      14
Switzerland      14
Canada           11
Spain             9
India             7
Brazil            7
Italy             7
Australia         7
Taiwan            6
Ireland           4
Russia            4
Sweden            3
Singapore         3
Mexico            2
Venezuela         1
Finland           1
Turkey            1
Luxembourg        1
Indonesia         1
Belgium           1
Denmark           1
Saudi Arabia      1
Malaysia          1
Norway            1
Thailand          1
Israel            1
U.A.E             1
Name: country, dtype: int64

In [61]:
countries_value['India']

7

In [63]:
north_america= countries_value[['USA', 'Canada', 'Mexico']]
north_america

USA       132
Canada     11
Mexico      2
Name: country, dtype: int64

In [64]:
big_movers=f500.loc[['Aviva', 'HP','JD.com', 'BHP Billiton'],['rank', 'previous_rank']] 
big_movers

rank  previous_rank
Aviva           90            279
HP             194             48
JD.com         261            366
BHP Billiton   350            168

In [65]:
bottom_companies= f500.loc['National Grid':'AutoNation', ['rank', 'sector', 'country']]
bottom_companies

rank              sector  country
National Grid                           491              Energy  Britain
Dollar General                          492           Retailing      USA
Telecom Italia                          493  Telecommunications    Italy
Xiamen ITG Holding Group                494         Wholesalers    China
Xinjiang Guanghui Industry Investment   495         Wholesalers    China
Teva Pharmaceutical Industries          496         Health Care   Israel
New China Life Insurance                497          Financials    China
Wm. Morrison Supermarkets               498  Food & Drug Stores  Britain
TUI                                     499   Business Services  Germany
AutoNation                              500           Retailing      USA